# Name of workflow
name: 'project test'

# Trigger the workflow on push or pull request

on:
    - push
    - pull_request

env:
    CI: true

jobs:
   build:

   # The type of machine to run the job on
   runs-on: ubuntu-latest

    strategy:
      # Node version list
    matrix:
        node-version: [17.x]

    steps:
       #Check-out repository under GitHub workspace
       # https://github.com/actions/checkout
     - uses: actions/checkout@v3
       # Step's name
     - name: Use Node ${{ matrix.node }}
     # Configures the node version used on GitHub-hosted runners
     # https://github.com/actions/setup-node
     uses: actions/setup-node@v3
     # The Node.js version to configure
      with:
         node-version: ${{ matrix.node }}
         cache: 'npm'
     # Run install project
     - name: npm install
     run: |        
       make install
     env:
       CI: true
     - name: Run linter
     run: |
       make lint
     - name: Test & publish code coverage
      # Publish code coverage on Code Climate
      # https: // github.com/paambati/codeclimate-action
      uses: paambaati/codeclimate-action@v3.2.0
      # Add Code Climate secret key
      env:
         CC_TEST_REPORTER_ID: ${{ secrets.TEST_COVERAGE }}
       with:
       coverageCommand: make test-coverage
       debug: true
